### ISSUE TITLE
catch Summon search api's HTTPError: 429 Client Error

### ISSUE THREAD

**Issue by cummingsm** [gwu-libraries/launchpad#1002]

**Comment by dchud** [comment]
Note: to test, tail the apache error.log and look for something like the following:

```
[Thu Apr 02 14:35:25 2015] [error] [02/Apr/2015 14:35:25] ERROR [ui.views:499] Summon error: 429 Client Error:
[Thu Apr 02 14:35:25 2015] [error] [02/Apr/2015 14:35:25] ERROR [ui.views:502] 1 retries, sleeping 1s and retrying
```

In my testing it has always worked the second time.  Note that this reuses the existing setting SER_SOL_API_MAX_ATTEMPTS so it won't go past three attempts.  A third failure will lead to email like we already receive.

**Comment by dchud** [comment]
logger.error() was not a good idea.  just remove these.
