### ISSUE TITLE
update Django to a later version.

### ISSUE THREAD

**Issue by cummingsm** [gwu-libraries/launchpad#1005]
Update to 1.6 first, then test, then test, and then update to 1.7

**Comment by dchud** [comment]
1.6 seems to check out just fine w/launchpad-autotest. running 1.7 now.

**Comment by dchud** [comment]
1.7 introduces migrations, which appear to be mandatory in a way I haven't found a simple way to route around yet.  For now, targeting 1.6. We can re-evaluate again later.

Note that the changes to persistent connections (https://docs.djangoproject.com/en/1.8/ref/databases/#persistent-database-connections) and the ```CONN_MAX_AGE``` setting might help us with the connection issues we've seen.

**Comment by dchud** [comment]
Note that the old ```from django.utils import simplejson as json``` shim was removed as of 1.5: https://docs.djangoproject.com/en/1.8/releases/1.5/#simplejson-deprecation

Replacing with ```import json``` and testing.

**Comment by cummingsm** [comment]
Closed by 1031.
