### ISSUE TITLE
add more information to our generic error page

### ISSUE THREAD

**Issue by cummingsm** [gwu-libraries/launchpad#1022]
The current text is shown below. It would be better to have a bit more explanation. For example, "No items were found matching the item number, or there may have been a problem retrieving the item. Library staff have been notified of the problem. We regret the inconvenience. "

No items found
We're sorry, but we cannot find that.
Try a keyword search:

**Comment by dchud** [comment]
So this would only be on 4xx / 5xx error response screens?  A normal/legit "not found" response with no errors should probably just return that simpler message still.

**Comment by kerchner** [comment]
In addition to what's noted above about the opportunity to add specificity when a search yelds no results, I also see that certain patterns aren't caught by the app and end up at the default tomcat error page, such as: http://findit.library.gwu.edu/abcde

You might consider routing to a page which lists valid URL patterns, e.g.
/item/<itemnumber>
/search/
/search?q=some+term
/catalog/
etc.

**Comment by dchud** [comment]
@kerchner the trick with that is that the root url is proxying a third-party service.  We make explicit exceptions to that in the apache config for launchpad.  It's possible that it's an inside-out approach but we can look at the whole picture again together.
