### ISSUE TITLE
get added authors error on Russian language encoding

### ISSUE THREAD

**Issue by cummingsm** [gwu-libraries/launchpad#1024]
bibid 2530157
‡6 880-06 ‡a Vysotskiĭ, S. S. ‡q (Sergeĭ Sergeevich), ‡d 1908- ‡t Zvukovye izmenenii︠a︡ ne vlii︠a︡i︠u︡shchie na osnovnye cherty fonologicheskogo stroi︠a︡ govorov. ‡0 http://id.loc.gov/authorities/names/no93014990

DjangoUnicodeDecodeError: 'utf8' codec can't decode bytes in position 148-149: unexpected end of data. You passed in 'Vysotskii\xcc\x86, S. S. (Sergei\xcc\x86 Sergeevich), 1908- Zvukovye izmenenii\xef\xb8\xa0a\xef\xb8\xa1 ne vlii\xef\xb8\xa0a\xef\xb8\xa1i\xef\xb8\xa0u\xef\xb8\xa1shchie na osnovnye cherty fonologicheskogo stroi\xef\xb8\xa0a\xef\xb8'

**Comment by cummingsm** [comment]
This was not resolved by the updated that fixed related issue #1057. The string beginning with 'Vysotsk' appears on the second of two 700 tags:

![image](https://cloud.githubusercontent.com/assets/1033656/12428642/ca94d04e-beb3-11e5-9a99-585f9d77a445.png)

**Comment by lwrubel** [comment]
Closed with #1094.
