### ISSUE TITLE
List only the first few subject headings, provide a toggle to view more

### ISSUE THREAD

**Issue by cummingsm** [gwu-libraries/launchpad#1026]
In Summon search results, there are many titles that have long lists of subject headings. Add a hyperlink More / Less toggle.

example search http://bit.ly/1gphRML

In closed issue #134 we added a toggle for long lists of serials on the item page. A similar toggle could be applied to the item page on the Details tab where the subjects are also listed.  We have a similar open issue #736 to collapse long lists of recent issue statements.

**Comment by lwrubel** [comment]
If we're only showing a few, do we still want them alphabetized? Seems like it would be better to keep the original order so more relevant headings are visible.

**Comment by cummingsm** [comment]
OK, but then when the list is expanded they won't be alphabetized. I guess
that's OK. It would be nice if they were de-duplicated. That may be a
separate ticket?

Thanks,

*Mike *

**Comment by lwrubel** [comment]
Agree, make the sorting of the subject headings another ticket.

**Comment by lwrubel** [comment]
Note that I used Bootstrap's collapse option for this, which is different from what we're using in the periodicals listing. I think this looks better and if you agree, we might consider changing the periodicals listing to do so as well (see #134) and use this when resolving #736.
