### ISSUE TITLE
template does not show details for the search isbn:1573870994

### ISSUE THREAD

**Issue by cummingsm** [gwu-libraries/launchpad#1030]
Although the facets for the record found by searching 1573870994 are displayed, the template doesn't display the title, author, or other details. However a description of the the record is in the raw data.

This search is one of many included in summon_tests.py 
The summon test fails, and Travis will not complete the build process.

**Comment by cummingsm** [comment]
Another example of the same is search result for 0312241186

**Comment by cummingsm** [comment]
The problem may be that the raw data does not include an "Institution" element such as

"Institution": [
"George Washington University (GW)"
],

and we don't handle that situation.

**Comment by cummingsm** [comment]
Now it does display. The Summon results seem to change for some unknown reason. Closing. No action required.

**Comment by cummingsm** [comment]
This problem cropped up again. Investigate how to handle cases like this

**Comment by lwrubel** [comment]
When this record was not displaying in the search results, the Summon raw view was showing one document from Howard, with no peer documents and no Institution field. There was a wrlc bibid in the record, for the Howard bib in WRLC Voyager. 

Today, when it does display, the Summon raw view shows a George Mason record, with a peerDocument for the HU record, still lacking an Institution field.
