### ISSUE TITLE
limit number of subjects in Refworks link

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/launchpad#1039]
The item's subjects are put in the URL to pass to Refworks. Some records have a lot of subjects and this makes the URL so long that it exceeds Refworks' limit on the length of a URL it will accept.

Example: http://findit.library.gwu.edu/item/3836230

**Comment by cummingsm** [comment]
This is new development as a consequence of the OCLC reclamation project which loaded enhanced bib records.

**Comment by lwrubel** [comment]
Cutoff seems to be around 2,100 characters. 

Limiting arbitrarily to three subject headings. Alternatively, we could use the MAX_SUBJECTS setting, but if that were set too high, it might still exceed the RefWorks URL length limit.
