### ISSUE TITLE
fix indent for location Gelman Special Collections

### ISSUE THREAD

**Issue by cummingsm** [gwu-libraries/launchpad#1055]
This location is not indented a couple of characters like the others. Example bibids: 3722505, 7593453, 6552934

**Comment by cummingsm** [comment]
I need to change 
{% if bib.FINDING_AID or item.TRIMMED_LOCATION_DISPLAY_NAME == 'GELMAN Special Collections'%}
 Gelman Special Collections 
to
{% if bib.FINDING_AID or item.TRIMMED_LOCATION_DISPLAY_NAME == 'GELMAN Special Collections'%} 
<div class='itemrow'>
Gelman Special Collections 
 <br />

**Comment by lwrubel** [comment]
Moved logic into itemrow div. There may be a better way to address the logic about what to display as the location name, taking into consideration temp location, finding aid info, and special collections. Suggest ticketing that separately if there's not a ticket already.
