### ISSUE TITLE
fix error processing utf-8 in added authors

### ISSUE THREAD

**Issue by cummingsm** [gwu-libraries/launchpad#1057]
Record looks normal in classic catalog. Has UTF-8

[launchpad-prod] ERROR: unable to render bibid: 11141189
File "/launchpad/current/launchpad/lp/ui/views.py", line 61, in item
    bib = voyager.get_bib_data(bibid)

  File "/launchpad/current/launchpad/lp/ui/voyager.py", line 153, in get_bib_data
    bib['AUTHORS'] = get_added_authors(bib)

  File "/launchpad/current/launchpad/lp/ui/voyager.py", line 60, in get_added_authors
    row = cursor.fetchone()

  File "/launchpad/m32_001/launchpad/ENV/lib/python2.7/site-packages/django/db/backends/oracle/base.py", line 752, in fetchone
    return _rowfactory(row, self.cursor)

  File "/launchpad/m32_001/launchpad/ENV/lib/python2.7/site-packages/django/db/backends/oracle/base.py", line 837, in _rowfactory
    value = to_unicode(value)

  File "/launchpad/m32_001/launchpad/ENV/lib/python2.7/site-packages/django/db/backends/oracle/base.py", line 848, in to_unicode
    return force_text(s)

  File "/launchpad/m32_001/launchpad/ENV/lib/python2.7/site-packages/django/utils/encoding.py", line 115, in force_text
    raise DjangoUnicodeDecodeError(s, *e.args)

DjangoUnicodeDecodeError: 'utf8' codec can't decode byte 0xcc in position 149: unexpected end of data. You passed in 'Bdud-\xca\xbejoms \xca\xbeJigs-bral-ye-s\xcc\x81es-rdo-rje, 1904-1987. Zab gsan\xcc\x87 mkha\xca\xbe \xca\xbegro\xca\xbei sn\xcc\x83in\xcc\x87 thig gi sn\xcc\x87on \xca\xbegro\xca\xbei n\xcc\x87ag \xca\xbedon zun\xcc\x87 \xca\xbejug lam gyi shin\xcc' (<type 'str'>)

**Comment by cummingsm** [comment]
Similar issue with bibid  6538636

**Comment by lwrubel** [comment]
I may have fixed this, but I could use another few test cases. Specifically, it would be helpful to have one with more than two added authors.

**Comment by cummingsm** [comment]
10049297
Kühne, Winrich
<http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4QsPwxW3Myblv8qlXbqW3LPXXH56dHpdf5G36yY02?t=http%3A%2F%2Ffindit.library.gwu.edu%2Fsearch%3Fq%3DAuthor%3A%2522Ku%25CC%2588hne%2C%2520Winrich%2522&si=4805465747226624&pi=ce3f2419-8b41-48d5-b0c1-27f4999ec854>
 ; Cross, Peter
<http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4QsPwxW3Myblv8qlXbqW3LPXXH56dHpdf5G36yY02?t=http%3A%2F%2Ffindit.library.gwu.edu%2Fsearch%3Fq%3DAuthor%3A%2522Cross%2C%2520Peter%2522&si=4805465747226624&pi=ce3f2419-8b41-48d5-b0c1-27f4999ec854>
 ; Schümer, Tanja
<http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4QsPwxW3Myblv8qlXbqW3LPXXH56dHpdf5G36yY02?t=http%3A%2F%2Ffindit.library.gwu.edu%2Fsearch%3Fq%3DAuthor%3A%2522Schu%25CC%2588mer%2C%2520Tanja%2522&si=4805465747226624&pi=ce3f2419-8b41-48d5-b0c1-27f4999ec854>
 ; Stiftung Wissenschaft und Politik
<http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4QsPwxW3Myblv8qlXbqW3LPXXH56dHpdf5G36yY02?t=http%3A%2F%2Ffindit.library.gwu.edu%2Fsearch%3Fq%3DAuthor%3A%2522Stiftung%2520Wissenschaft%2520und%2520Politik%2522&si=4805465747226624&pi=ce3f2419-8b41-48d5-b0c1-27f4999ec854>


10335537
Takaoka, Kazuya
<http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4QsPwxW3Myblv8qlXbqW3LPXXH56dHpdf5G36yY02?t=http%3A%2F%2Ffindit.library.gwu.edu%2Fsearch%3Fq%3DAuthor%3A%2522Takaoka%2C%2520Kazuya%2522&si=4805465747226624&pi=ce3f2419-8b41-48d5-b0c1-27f4999ec854>
 ; Uragami, Mitsuru, 1951-
<http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4QsPwxW3Myblv8qlXbqW3LPXXH56dHpdf5G36yY02?t=http%3A%2F%2Ffindit.library.gwu.edu%2Fsearch%3Fq%3DAuthor%3A%2522Uragami%2C%2520Mitsuru%2C%25201951-%2522&si=4805465747226624&pi=ce3f2419-8b41-48d5-b0c1-27f4999ec854>
 ; Nakamura, Hideki
<http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4QsPwxW3Myblv8qlXbqW3LPXXH56dHpdf5G36yY02?t=http%3A%2F%2Ffindit.library.gwu.edu%2Fsearch%3Fq%3DAuthor%3A%2522Nakamura%2C%2520Hideki%2522&si=4805465747226624&pi=ce3f2419-8b41-48d5-b0c1-27f4999ec854>
 ; 高岡一弥
<http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4QsPwxW3Myblv8qlXbqW3LPXXH56dHpdf5G36yY02?t=http%3A%2F%2Ffindit.library.gwu.edu%2Fsearch%3Fq%3DAuthor%3A%2522%25E9%25AB%2598%25E5%25B2%25A1%25E4%25B8%2580%25E5%25BC%25A5%2522&si=4805465747226624&pi=ce3f2419-8b41-48d5-b0c1-27f4999ec854>
 ; 浦上満, 1951-
<http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4QsPwxW3Myblv8qlXbqW3LPXXH56dHpdf5G36yY02?t=http%3A%2F%2Ffindit.library.gwu.edu%2Fsearch%3Fq%3DAuthor%3A%2522%25E6%25B5%25A6%25E4%25B8%258A%25E6%25BA%2580%2C%25201951-%2522&si=4805465747226624&pi=ce3f2419-8b41-48d5-b0c1-27f4999ec854>
 ; 中村英樹
<http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4QsPwxW3Myblv8qlXbqW3LPXXH56dHpdf5G36yY02?t=http%3A%2F%2Ffindit.library.gwu.edu%2Fsearch%3Fq%3DAuthor%3A%2522%25E4%25B8%25AD%25E6%259D%2591%25E8%258B%25B1%25E6%25A8%25B9%2522&si=4805465747226624&pi=ce3f2419-8b41-48d5-b0c1-27f4999ec854>


10478572
Gacitúa-Marió, Estanislao
<http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4QsPwxW3Myblv8qlXbqW3LPXXH56dHpdf5G36yY02?t=http%3A%2F%2Ffindit.library.gwu.edu%2Fsearch%3Fq%3DAuthor%3A%2522Gacitu%25CC%2581a-Mario%25CC%2581%2C%2520Estanislao%2522&si=4805465747226624&pi=ce3f2419-8b41-48d5-b0c1-27f4999ec854>
 ; Sojo, Carlos
<http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4QsPwxW3Myblv8qlXbqW3LPXXH56dHpdf5G36yY02?t=http%3A%2F%2Ffindit.library.gwu.edu%2Fsearch%3Fq%3DAuthor%3A%2522Sojo%2C%2520Carlos%2522&si=4805465747226624&pi=ce3f2419-8b41-48d5-b0c1-27f4999ec854>
 ; Davis, Shelton H
<http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4QsPwxW3Myblv8qlXbqW3LPXXH56dHpdf5G36yY02?t=http%3A%2F%2Ffindit.library.gwu.edu%2Fsearch%3Fq%3DAuthor%3A%2522Davis%2C%2520Shelton%2520H%2522&si=4805465747226624&pi=ce3f2419-8b41-48d5-b0c1-27f4999ec854>
 ; World Bank
<http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4QsPwxW3Myblv8qlXbqW3LPXXH56dHpdf5G36yY02?t=http%3A%2F%2Ffindit.library.gwu.edu%2Fsearch%3Fq%3DAuthor%3A%2522World%2520Bank%2522&si=4805465747226624&pi=ce3f2419-8b41-48d5-b0c1-27f4999ec854>

 10336187
Ma, Zhengang
<http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4QsPwxW3Myblv8qlXbqW3LPXXH56dHpdf5G36yY02?t=http%3A%2F%2Ffindit.library.gwu.edu%2Fsearch%3Fq%3DAuthor%3A%2522Ma%2C%2520Zhengang%2522&si=4805465747226624&pi=ce3f2419-8b41-48d5-b0c1-27f4999ec854>
 ; Zhen, Bingxi
<http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4QsPwxW3Myblv8qlXbqW3LPXXH56dHpdf5G36yY02?t=http%3A%2F%2Ffindit.library.gwu.edu%2Fsearch%3Fq%3DAuthor%3A%2522Zhen%2C%2520Bingxi%2522&si=4805465747226624&pi=ce3f2419-8b41-48d5-b0c1-27f4999ec854>
 ; 马振岗
<http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4QsPwxW3Myblv8qlXbqW3LPXXH56dHpdf5G36yY02?t=http%3A%2F%2Ffindit.library.gwu.edu%2Fsearch%3Fq%3DAuthor%3A%2522%25E9%25A9%25AC%25E6%258C%25AF%25E5%25B2%2597%2522&si=4805465747226624&pi=ce3f2419-8b41-48d5-b0c1-27f4999ec854>
 ; 甄炳禧
<http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4QsPwxW3Myblv8qlXbqW3LPXXH56dHpdf5G36yY02?t=http%3A%2F%2Ffindit.library.gwu.edu%2Fsearch%3Fq%3DAuthor%3A%2522%25E7%2594%2584%25E7%2582%25B3%25E7%25A6%25A7%2522&si=4805465747226624&pi=ce3f2419-8b41-48d5-b0c1-27f4999ec854>
 ; China Documentation Center
<http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4QsPwxW3Myblv8qlXbqW3LPXXH56dHpdf5G36yY02?t=http%3A%2F%2Ffindit.library.gwu.edu%2Fsearch%3Fq%3DAuthor%3A%2522China%2520Documentation%2520Center%2522&si=4805465747226624&pi=ce3f2419-8b41-48d5-b0c1-27f4999ec854>


6062860
Soi︠a︡, Anton
<http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4QsPwxW3Myblv8qlXbqW3LPXXH56dHpdf5G36yY02?t=http%3A%2F%2Ffindit.library.gwu.edu%2Fsearch%3Fq%3DAuthor%3A%2522Soi%25EF%25B8%25A0a%25EF%25B8%25A1%2C%2520Anton%2522&si=4805465747226624&pi=ce3f2419-8b41-48d5-b0c1-27f4999ec854>
 ; Grebenshchikov, Boris
<http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4QsPwxW3Myblv8qlXbqW3LPXXH56dHpdf5G36yY02?t=http%3A%2F%2Ffindit.library.gwu.edu%2Fsearch%3Fq%3DAuthor%3A%2522Grebenshchikov%2C%2520Boris%2522&si=4805465747226624&pi=ce3f2419-8b41-48d5-b0c1-27f4999ec854>
 ; Gunit︠s︡kiĭ, Anatoliĭ
<http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4QsPwxW3Myblv8qlXbqW3LPXXH56dHpdf5G36yY02?t=http%3A%2F%2Ffindit.library.gwu.edu%2Fsearch%3Fq%3DAuthor%3A%2522Gunit%25EF%25B8%25A0s%25EF%25B8%25A1kii%25CC%2586%2C%2520Anatolii%25CC%2586%2522&si=4805465747226624&pi=ce3f2419-8b41-48d5-b0c1-27f4999ec854>
 ; Romanov, Di︠u︡sha, 1956-2000
<http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4QsPwxW3Myblv8qlXbqW3LPXXH56dHpdf5G36yY02?t=http%3A%2F%2Ffindit.library.gwu.edu%2Fsearch%3Fq%3DAuthor%3A%2522Romanov%2C%2520Di%25EF%25B8%25A0u%25EF%25B8%25A1sha%2C%25201956-2000%2522&si=4805465747226624&pi=ce3f2419-8b41-48d5-b0c1-27f4999ec854>
 ; Leonidov, Maksim
<http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4QsPwxW3Myblv8qlXbqW3LPXXH56dHpdf5G36yY02?t=http%3A%2F%2Ffindit.library.gwu.edu%2Fsearch%3Fq%3DAuthor%3A%2522Leonidov%2C%2520Maksim%2522&si=4805465747226624&pi=ce3f2419-8b41-48d5-b0c1-27f4999ec854>
 ; Shkli︠a︡rskiĭ, Edmund
<http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4QsPwxW3Myblv8qlXbqW3LPXXH56dHpdf5G36yY02?t=http%3A%2F%2Ffindit.library.gwu.edu%2Fsearch%3Fq%3DAuthor%3A%2522Shkli%25EF%25B8%25A0a%25EF%25B8%25A1rskii%25CC%2586%2C%2520Edmund%2522&si=4805465747226624&pi=ce3f2419-8b41-48d5-b0c1-27f4999ec854>
 ; Vasilʹev, Aleksandr
<http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XX4QsPwxW3Myblv8qlXbqW3LPXXH56dHpdf5G36yY02?t=http%3A%2F%2Ffindit.library.gwu.edu%2Fsearch%3Fq%3DAuthor%3A%2522Vasil%25CA%25B9ev%2C%2520Aleksandr%2522&si=4805465747226624&pi=ce3f2419-8b41-48d5-b0c1-27f4999ec854>


SELECT BIB_INDEX.BIB_ID, Count(BIB_INDEX.INDEX_CODE) AS CountOfINDEX_CODE
FROM (BIB_INDEX INNER JOIN BIB_TEXT ON BIB_INDEX.BIB_ID = BIB_TEXT.BIB_ID)
INNER JOIN BIB_MASTER ON BIB_INDEX.BIB_ID = BIB_MASTER.BIB_ID
WHERE (((BIB_INDEX.INDEX_CODE)="700H") AND (Not (BIB_TEXT.LANGUAGE)="eng"))
GROUP BY BIB_INDEX.BIB_ID, BIB_MASTER.SUPPRESS_IN_OPAC,
BIB_MASTER.LIBRARY_ID
HAVING (((BIB_INDEX.BIB_ID) Between "6000000" And "6550000") AND
((Count(BIB_INDEX.INDEX_CODE))>2) AND ((BIB_MASTER.SUPPRESS_IN_OPAC)="N")
AND ((BIB_MASTER.LIBRARY_ID)="7"));


Thanks,

*Mike *

**Comment by cummingsm** [comment]
I checked out this branch and found all five of the previous bibids that were are problem are working now.

**Comment by lwrubel** [comment]
It looks like the DjangoUnicodeDecodeError is being raised in get_added_authors when the problem row is read into a python data type (row = cursor.fetchone()). The code I checked in basically skips over the row. So if there is another problem row, it's going to have an error raised and not display the page. Not sure if there is some way to understand whether that is a possible occurrence here?

Once it's skipped over, you can't go back and look at that row again (scrolling not supported in cx_Oracle cursor in all the research I've done), you'd have to re-execute the query. Not sure that helps anyway.

I haven't been able to find a way to intercept the info and change the encoding. So this seems like a data problem in the end.

**Comment by lwrubel** [comment]
Looks like #1024 is a good example of multiple occurrences of a problem data field. Will work on that.
