### ISSUE TITLE
fix error processing utf-8 in isbn string

### ISSUE THREAD

**Issue by cummingsm** [gwu-libraries/launchpad#1058]
[launchpad-prod] ERROR: unable to render bibid: 13988966
 File "/launchpad/current/launchpad/lp/ui/views.py", line 61, in item
    bib = voyager.get_bib_data(bibid)

  File "/launchpad/current/launchpad/lp/ui/voyager.py", line 186, in get_bib_data
    bib.get('TITLE', ''))

  File "/launchpad/current/launchpad/lp/ui/voyager.py", line 329, in get_related_bibids
    results = _make_dict(cursor)

  File "/launchpad/current/launchpad/lp/ui/voyager.py", line 32, in _make_dict
    for row in cursor.fetchall()

  File "/launchpad/m32_001/launchpad/ENV/lib/python2.7/site-packages/django/db/backends/oracle/base.py", line 762, in fetchall
    for r in self.cursor.fetchall()])

  File "/launchpad/m32_001/launchpad/ENV/lib/python2.7/site-packages/django/db/backends/oracle/base.py", line 837, in _rowfactory
    value = to_unicode(value)

  File "/launchpad/m32_001/launchpad/ENV/lib/python2.7/site-packages/django/db/backends/oracle/base.py", line 848, in to_unicode
    return force_text(s)

  File "/launchpad/m32_001/launchpad/ENV/lib/python2.7/site-packages/django/utils/encoding.py", line 115, in force_text
    raise DjangoUnicodeDecodeError(s, *e.args)

DjangoUnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 15: invalid continuation byte. You passed in "235433141X (Mus\xe9e d'Orsay)" (<type 'str'>)

**Comment by cummingsm** [comment]
another example: item 14380241
 File "/launchpad/current/launchpad/lp/ui/views.py", line 90, in item
    bib['RELATED_ISBN_LIST'] = list(set(voyager.get_related_isbns(bibs)))
DjangoUnicodeDecodeError: 'utf8' codec can't decode byte 0xe8 in position 14: invalid continuation byte. You passed in '3727293551 (St\xe8ampfli)' (<type 'str'>)

**Comment by lwrubel** [comment]
@cummingsm, when we talked about this one last week, it sounded like you were considering some alternative approaches related to the data and the Voyager query. Is that still the case? Wondering if I should carry on working on this through editing various voyager.py functions, or wait for results of a data-side approach.

**Comment by cummingsm** [comment]
You may be referring to the other ISBN related issue 1063 "provide show/hide link for the ISBN list." Instead of retrieving an excessively long list of ISBNs, the Voyager query was modified to return a limited number of ISBNs.  That update does not handle anything different as far as UTF encoding-decoding though.

**Comment by cummingsm** [comment]
I tracked down the problematic Voyager data records and fixed them. In almost every case, it was not the bib record listed in the Django exception error, but instead a related record found by a matching standard number. In the original problem case, bibid 13988966, it was related GT record 13901715 that had corrupt data:  
![image](https://cloud.githubusercontent.com/assets/1033656/12755331/f4795634-c99c-11e5-9896-98ea11ffd96d.png)

I edited those fields, and now it works fine.

**Comment by lwrubel** [comment]
This is a super-helpful finding, Mike. I had been working on the assumption
that it was the original bibid, misled by the fact that I was seeing
diacritics in that one as well. It would still be nice if launchpad didn't
flail when it encountered that kind of data, but at least we understand the
problem better.

**Comment by lwrubel** [comment]
Closing as wontfix. Source of problem is non-WRLC Voyager sourced records as described above. Fix or report to WRLC on a case-by-case basis.

**Comment by cummingsm** [comment]
Fix easily by searching Voyager Catalog using index "IBSN (ISBN-13s will match ISBN-10s)" and / or index "ISBN (020a)". Check the GT-owned bib record(s). Delete characters that appear to be CJK.
