### ISSUE TITLE
move logic about "available to all" out of item.html

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/launchpad#1060]
item.html currently has logic that looks for strings in the 856 URL to determine whether a resource is licensed or "Available to all". Move logic to voyager.py or elsewhere and pass to template.

**Comment by lwrubel** [comment]
When another institution's full text link is available to all, I'm wondering why we treat these links differently. Instead of putting the words "Available to all" under the full text link (where the lock icon and campus note would be), why not just put the blue "online" button there? 

See for example:
http://findit.library.gwu.edu/item/12698379

**Comment by cummingsm** [comment]
Good point. It doesn't have to say Available to all.

**Comment by lwrubel** [comment]
Expanding scope of this ticket to include simplifying the 856 links sections of item.html, so that "online" buttons, links, bound_with, labels created from new ONLINE element in json. To be ticketed separately:
* evaluating why there is ELECTRONIC_DATA and marc856list
* possibly consolidating and/or writing directly to new ONLINE element
* reviewing duplication of audio_tags and video_tags
