### ISSUE TITLE
Marymount links to cover images

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/launchpad#1065]
Marymount has cover image jpg filenames in some records' 856 $u. Launchpad is creating a non-working link to the jpg, "available to all".
 
http://findit.library.gwu.edu/item/12932387

**Comment by cummingsm** [comment]
Could this fix be wrapped in to the changes from #1060 ?

**Comment by lwrubel** [comment]
The problem seems more that the url is lacking an http:// and doesn't work, than the fact that it's a jpg. There may be reasons to link to an image as an online resource? I don't know, but am addressing this by checking that the url starts with http://

BTW, the example book here is a good one, worth reading.

**Comment by lwrubel** [comment]
Fixed in #1064 by looking for http (in order to also catch https) in URL.
