### ISSUE TITLE
edit link logic to exclude non-gw Springer links that may not provide full text access

### ISSUE THREAD

**Issue by cummingsm** [gwu-libraries/launchpad#1070]
see http://findit.library.gwu.edu/item/6227764
the link is
http://link.springer.com/book/10.1007/b138701
and the patron has limited content, but not full text

**Comment by lwrubel** [comment]
Check with CU and they are fixing the records so that the URLs have their proxy prefix. If these sorts of links occur more (in a way that's not a mistake), we might consider looking for the word "restricted" in the 852 $z.

**Comment by lwrubel** [comment]
CUA has reloaded the records with the unproxied links, so this particular problem does not exist anymore.
