### ISSUE TITLE
identify problem with GW record not displaying

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/launchpad#1077]
WRLC bibid 7765645 exists, but launchpad is giving a 404 (even on dev with DEBUG=True)
http://findit.library.gwu.edu/item/7765645

Item in WRLC catalog
http://catalog.wrlc.org/cgi-bin/Pwebrecon.cgi?BBID=7765645

Thought it might be a problem with diacritics in the author field, but this one works:
http://findit.library.gwu.edu/item/12343288

**Comment by cummingsm** [comment]
This is related to or the same as issue #1057 regarding utf-8 in added author tag. Also this particular record may actually have some corrupt diacritics. The bib record is suppressed too.

**Comment by cummingsm** [comment]
Record is suppressed. Closing this issue
