### ISSUE TITLE
GT links to loc catalog author bio are not full text links

### ISSUE THREAD

**Issue by cummingsm** [gwu-libraries/launchpad#1084]
This record links to http://catdir.loc.gov/catdir/enhancements/fy1318/2013434364-d.html
It should not display an Online button

http://findit.library.gwu.edu/item/13318936

**Comment by lwrubel** [comment]
BTW, this record looks like it has some other problem-- the author should be García Lorca, as it is in the original GT record, but it's gotten cut off along the way. The problem exists in WRLC Voyager, so it's not a launchpad issue.
