### ISSUE TITLE
use more Worldcat description when no Voyager record is available

### ISSUE THREAD

**Issue by cummingsm** [gwu-libraries/launchpad#1108]
A person be viewing a title in Worldcat, e.g., http://www.worldcat.org/title/brain/oclc/34473395 could select "Check Availability at GWU or request through ILL"

![image](https://cloud.githubusercontent.com/assets/1033656/13197262/5bd4b4d2-d7b6-11e5-9932-071b057dac24.png)

**even though Worldcat doesn't list any WRLC library**.  Our Worldcat API handles this scenario by displaying some information from the resultset returned from OCLC. We could show more of the resultset, and provide an explanation that the results are from OCLC.

For examples try /oclc/ and one of these numbers:    
609102750 34473395 34474496

Sample result: https://github.com/gwu-libraries/launchpad/wiki/sample-results-from-oclc-api

**Comment by cummingsm** [comment]
After the update the 

![image](https://cloud.githubusercontent.com/assets/1033656/13361399/74ee108c-dc8c-11e5-8ec0-e4bdd5000c12.png)

**Comment by StudioZut** [comment]
Looks great, I think this is really useful. 
Testing this for the PR I noticed that the second author link in example /oclc/34473395 doesn't return any results (http://gwdev-zut.wrlc.org:8888/search?q=Author:%22Thompson,%20Ian,%201964-%20illustrator.%22) and in example /oclc/34474496 the only author link also returns no results.

**Comment by cummingsm** [comment]
The author link a different problem unrelated to this work. The code for
building links includes a "role" from a subfield on the MARC tag we
shouldn't make part of the link (eg., illustrator).

If you remove the illustrator from the link, it works
http://gwdev-zut.wrlc.org:8888/search?q=Author:%22Thompson,%20Ian,%201964%22

Thanks,

*Mike *

On Tue, Mar 1, 2016 at 4:44 PM, Christian Aldridge <notifications@github.com
