### ISSUE TITLE
include the SMS link on electronic resources

### ISSUE THREAD

**Issue by cummingsm** [gwu-libraries/launchpad#1117]
Librarian requested SMS link for JSTOR DDA record example bibid 15904551

**Comment by lwrubel** [comment]
@cummingsm this seems to work fine, but I'd like to better understand the use case for it. Having a little button like that right up next to the clear, blue Online button doesn't seem ideal. I'm wondering if there are other approaches we could discuss.

**Comment by cummingsm** [comment]
This was requested by Robin Kinder.

**Comment by cummingsm** [comment]
We added the SMS link, but the icon is not noticeable next to the Online button; the only info the link passes to the SMS text is the title. Not as useful as getting the title and call number so that the user can retrieve a book from the shelves.
