### ISSUE TITLE
consider comment on advanced search re non-roman search

### ISSUE THREAD

**Issue by cummingsm** [gwu-libraries/launchpad#1177]
We noticed a problem searching Korean text as a title, reported it to Proquest. Their response was that the title and other searches don't work with the vernacular script content of the 8xx tags. They will add this feature as an **enhancement request.**

Searching vernacular script by keyword does work. Consider adding a note of some sort on the advanced search page that directs uses to use the keyword search fields. The not could appear between the Keyword and Exact Phrase or after Exact Phrase in the "Any Field" section at the top of the page (mockup in screen shot below)

![image](https://cloud.githubusercontent.com/assets/1033656/21394491/d2ed0e3e-c766-11e6-9bc2-b82206af5172.png)

**Comment by cummingsm** [comment]
Already have HTML placeholder text attribute. Will use that.

**Comment by lwrubel** [comment]
Can I suggest making the note briefer, e.g. "search in any language" or "search in any language, including Chinese, Japanese, Korean".

**Comment by cummingsm** [comment]
The message needs to indicate the keyword field can be for both general keyword and for vernacular title searches. 

How about:
"Search keywords or Titles in any language, including Chinese, Japanese, Korean, etc."
