### ISSUE TITLE
add link for stackmap

### ISSUE THREAD

**Issue by cummingsm** [gwu-libraries/launchpad#1189]
Max is working on a JavaScript package to direct users to the appropriate Gelman Stacks floor map. 

He suggested we provide a link in the form  "http://library.gwu.edu/about/maps/floorplans#stack-[squishedcallnumber] where [squishedcallnumber] is the LoC call number with spaces removed" on items from Gelman Stacks that have a library of congress call number. The link itself is to be determined. It could be text or an icon. 

Besides the link, the page would need to load Javascript Max would provide.

**Comment by lwrubel** [comment]
Closed by #1213
