### ISSUE TITLE
map openurl metadata and pass through into CLS forms

### ISSUE THREAD

**Issue by dchud** [gwu-libraries/launchpad#336]

**Comment by dchud** [comment]
Have we never implemented this?  Just ran into it with this link:

http://findit.library.gwu.edu/item/2375407?ctx_ver=Z39.88-2004&ctx_enc=info:ofi/enc:UTF-8&url_ver=Z39.88-2004&rfr_id=info:sid/Elsevier:SD&svc_val_fmt=info:ofi/fmt:kev:mtx:sch_svc&rft_val_fmt=info:ofi/fmt:kev:mtx:journal&rft.aulast=TREISMAN&rft.auinit=A&rft.date=1985&rft.issn=0734189X&rft.volume=31&rft.issue=2&rft.spage=156&rft.epage=177&rft.title=Computer%20Vision,%20Graphics,%20and%20Image%20Processing&rft.atitle=Preattentive%20processing%20in%20vision&rft_id=info:doi/10.1016/S0734-189X(85)80004-9

The ILL and Refworks links are filled out correctly with the openurl metadata, and the page head shows the article information, but the CLS links don't get the openurl bits.  I thought we'd long since added that already.

**Comment by cummingsm** [comment]
The CLS system is designed to accept a bib_id, not additional parameters. I
believe it would be up to WRLC to program the application on their side to
accept form field parameters.

*Mike *
