### ISSUE TITLE
API fallback when voyager unavailable

### ISSUE THREAD

**Issue by dchud** [gwu-libraries/launchpad#359]
When voyager experiences downtime, we can still use API calls to provide basic bibliographic information for incoming requests for standard public identifiers. 

For wrlc bibids, perhaps there's ways to find them in worldcat and go from there. 

A "voyager/local holdings unavailable" message of some sort would be appropriate below the fold.

**Comment by cummingsm** [comment]
bento detects problem and offers classic catalog
