### ISSUE TITLE
collapse long lists of recent issues with a toggle

### ISSUE THREAD

**Issue by cummingsm** [gwu-libraries/launchpad#736]
This is a good example. http://gwfindit-test.wrlc.org/item/2274255
Better to list a small number and then have a more / less toggle. 

Gelman Periodicals 
v.88:no.23 (2012:Aug. 6)-v.88:no.25 (2012: Aug. 27) 
v.89:no.1(2013:Feb. 11/18) 
v.89:no.2(2013:Feb. 25) 
v.89:no.3(2013:Mar. 4) 
v.89:no.4(2013:Mar.11) 
v.89:no.5(2013:Mar.18) 
v.89:no.6(2013:Mar.25) 
v.89:no.7(2013:Apr.1) 
v.89:no.8(2013:Apr.8) 
v.89:no.9(2013:Apr.15) 
v.89:no.10(2013:Apr.22) 
v.89:no.11(2013:Apr.29) 
v.89:no.12(2013:May 6)  etc etc

**Comment by lwrubel** [comment]
There are two places in item.html where "library-has" listings are handled. The example seen in http://gwfindit-test.wrlc.org/item/2274255 is where there are items (LIBRARY_HAS info comes from the mfhd_data.marc866list). I'm having trouble finding an example for the case where there are no items. @cummingsm can you point me to one?

**Comment by cummingsm** [comment]
Item 407093 may be a helpful use case. The AU holding 8783520 has no ITEMS
block, it has both MFHD_DATA.marc866list and LIBRARY_HAS

Thanks,

*Mike *

**Comment by lwrubel** [comment]
Yes, that is the right case. Now to find one like that which also has a long list of holdings to trigger the toggle to display.

**Comment by cummingsm** [comment]
Maybe item 2269275, CU has a null ITEMS block with 8 lines of LIBRARY_HAS

Thanks,

*Mike *

**Comment by lwrubel** [comment]
Thanks that one is useful. Another one to use is 756511 and the CU holding. 

With this change, the difference between the Show/Hide using bootstrap and the previous version (as resolved in #134 is more glaring, since they're on the same page.
