### ISSUE TITLE
consider reducing caching time period

### ISSUE THREAD

**Issue by cummingsm** [gwu-libraries/launchpad#869]
Why are we caching item views for 60 minutes? What is being cached, what benefit is there in caching for as long as 60 minutes? This cache keeps patrons from seeing live updates of catalog changes or the item status.

**Comment by dchud** [comment]
It was an arbitrary choice.  We could definitely dial it down... some caching seems better than none, for the case where a url is shared widely.

Probably the best way to decide is to look for patterns of heavy repeat use of a single url in the log files, and base a decision on what that data shows.

**Comment by dchud** [comment]
Note that this can be done simply by a configuration change to ```local_settings.py``` and ITEM_PAGE_CACHE_SECONDS during production deployment:

https://github.com/gwu-libraries/launchpad/blob/master/lp/lp/local_settings.py.template#L180

**Comment by cummingsm** [comment]
Updated production server settings ITEM_PAGE_CACHE_SECONDS and CACHES TIMEOUT to five minutes.
