### ISSUE TITLE
Item count (displayed over facets) can change as user paginates through results

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/launchpad#892]
http://findit.library.gwu.edu/search?q=architecture&page=1  - # of results shows as 392,677  (same for pages 5, 6, 16, and possibly others)
http://findit.library.gwu.edu/search?q=architecture&page=2  - # of results shows as 392,807 (same for pages 3, 4, 7, 8, 9, and others)

**Comment by edsu** [comment]
Not only that, if you reload just the first page of results a few times you will notice that they fluctuate.

    http://findit.library.gwu.edu/search?q=architecture&page=1

I reloaded it 10 times and noticed it flip between 331,794 and 394,344 3 times. I think it does this with any search, not just this particular one. 

Unfortunately, this is data that is coming directly back from Summon's Search API. It's the `recordCount` property.  I suggest we file a ticket with Serial Solutions explaining that the number is not constant. It seems like maybe they have multiple backend indexes, and they are out of sync somehow?

**Comment by cummingsm** [comment]
This is working now, the numbers remain consistent
