### ISSUE TITLE
check for proxy in url on other library links, if not don't show lock

### ISSUE THREAD

**Issue by cummingsm** [gwu-libraries/launchpad#936]
other libraries have some links that do not require authentication. their url will not contain proxy. In that case, don't display the lock icon. If not proxy and not serialssolutions

eg: 12643113  GT =no lock icon, it is just a link to metropolitan museum of art website
eg: 5225053    GT =no lock icon, it is a link to ERIC available to all

eg: 5713936   = lock icon  eresources from other libraries, the links don't have proxy but they have serialssolutions and those are authenticated
eg: 10335341 = lock icon if resoruce is EBL library like Gallaudet in this example 

eg: 7374222  GT= lock icon because it has a proxy link. 
eg: 12007317 GT and HU = lock icon they have proxy link

**Comment by lwrubel** [comment]
Additional cases: 
ebl links are restricted (they later direct the user to authenticate). They need a lock icon. See GA ebook holding:
10335341

**Comment by cummingsm** [comment]
Added eblib to resources to retain lock icon.
