### ISSUE TITLE
Add loading spinner

### ISSUE THREAD

**Issue by StudioZut** [gwu-libraries/launchpad#938]
Consider adding a 'page loading' spinner to avoid the blank page that can sometimes last for awhile when coming from Bento results to Launchpad.
Possibly use Font Awesome 'fa-spinner' : http://fortawesome.github.io/Font-Awesome/examples/#spinning

**Comment by edsu** [comment]
I'm confused where this spinner would go. Would it be in Bento? For it to be in Launchpad we would need to render an initial page with empty search results and then fetch them w/ an ajax call.

**Comment by cummingsm** [comment]
Ed,
This is a low priority issue. Someone suggested a 'spinner' for  (rare)
times when a long delay occurs in loading. I'm not sure if they meant on
the search results or on the launchpad item page. Chris just posted the
issue as something to consider.

// mobile

On Jan 17, 2015, at 3:08 PM, Ed Summers <notifications@github.com> wrote:

I'm confused where this spinner would go. Would it be in Bento? For it to
be in Launchpad we would need to render an initial page with empty search
results and then fetch them w/ an ajax call.

—
Reply to this email directly or view it on GitHub
<https://github.com/gwu-libraries/launchpad/issues/938#issuecomment-70382250>
.
