### ISSUE TITLE
Update the blue button styling

### ISSUE THREAD

**Issue by StudioZut** [gwu-libraries/launchpad#946]
Consider updating the 'blue button' style we are using across several apps. Consider flattening, possibly with layered shadow, squarer (or square) corners. Consider including Font Awesome icon to indicate 'link' or 'download' or 'content' etc.

**Comment by cummingsm** [comment]
Chris, consider making the button color change onmouseover?

**Comment by StudioZut** [comment]
Mike, good suggestion!

**Comment by StudioZut** [comment]
I have a working version on a branch: http://gwdev-zut.wrlc.org:8888/item/13409119

**Comment by cummingsm** [comment]
I  see you have a font awesome laptop icon representing online. That seems good. Shadow is fine. What if the shadow was there without rolling over the button, and the rollover effect instead was to change the color (darker blue for example)?

**Comment by StudioZut** [comment]
I will give that a shot.

**Comment by StudioZut** [comment]
You can see the changes now: http://gwdev-zut.wrlc.org:8888/item/13409119

**Comment by cummingsm** [comment]
The mouseover effect is similar to the one seen by mouseover of the
'information' icon in the call number header. This is good.

Thanks,

*Mike *

**Comment by StudioZut** [comment]
I adjusted it to an exact match on both states: http://gwdev-zut.wrlc.org:8888/item/13409119

**Comment by StudioZut** [comment]
I removed the box-shadow. Now that we've matched the link colors I think it's more consistent.

**Comment by StudioZut** [comment]
Next steps: 
Consider three sizes (classname-sm, -med, -lg) etc.
Consider dropping text to just 'online' followed by icon for media type (audio, video, text).
Build mockups to share with group.

**Comment by StudioZut** [comment]
This is the new version (same size) with the shortened text and a new icon
![screenshot 2015-02-26 at 10 09 01 am](https://cloud.githubusercontent.com/assets/1031373/6394455/a5e03ae2-bd9f-11e4-955c-77adfe764d7e.png)

**Comment by StudioZut** [comment]
Screenshots
![screen shot with book icon](https://cloud.githubusercontent.com/assets/1031373/6621320/52a81936-c8ac-11e4-81f0-cb0c351f64bf.png)
With book icon
![screen shot with book icon lg](https://cloud.githubusercontent.com/assets/1031373/6621325/56a75254-c8ac-11e4-9d7f-bd1fa4a6b674.png)
Larger with book icon
![screen shot with audio icon](https://cloud.githubusercontent.com/assets/1031373/6621345/765873f8-c8ac-11e4-8524-304495600c1b.png)
With audio icon
![screen shot with video icon](https://cloud.githubusercontent.com/assets/1031373/6621353/805b5d48-c8ac-11e4-984e-a73f16177368.png)
With video icon
![screen shot bento with book icon](https://cloud.githubusercontent.com/assets/1031373/6621355/870acd5e-c8ac-11e4-8bd5-c28912ce5021.png)
Bento with book icon

**Comment by StudioZut** [comment]
Finalize css/html and pull request by March 16th/17th

**Comment by cummingsm** [comment]
closing this it is replaced by a subsequent issue
