### ISSUE TITLE
add a browse subject headings feature

### ISSUE THREAD

**Issue by cummingsm** [gwu-libraries/launchpad#974]
Create a query that will search WRLC'S Voyager subject headings. The query results will be a list of the subjects headings, and the number of titles that have the subject headings. The user should be able to click the number of titles link to see a list of those titles. Clicking one of the titles would go to that item page.  

See: http://catalog.wrlc.org/cgi-bin/Pwebrecon.cgi?Search_Arg=cuba%20history&Search_Code=SUBJ_&SL=None&CNT=25&DB=local

Add link to the displayed subject headings in search results and on the detail tab which passes the heading terms to the new query.

**Comment by dchud** [comment]
+1.  We first talked about doing this a long time ago - seems like the right approach.

**Comment by cummingsm** [comment]
I have developed the queries that will (1) find exact matches on a subject heading, and (2) that can return a browsable sorted list of subject headings.
